//Throw, and Try...Catch...Finally

try {
    addlert("welcome!")         //adddlert as an error
} catch (error) {
    console.log(error.message); 
}

